apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-06bc31ff7e510a8e1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc
spec:
  storageClassName: ""
  volumeName: efs-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efsstatic-pod
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: efs-vol
          mountPath: /usr/share/nginx/html
  volumes:
    - name: efs-vol
      persistentVolumeClaim:
        claimName: efs-pvc
