apiVersion: v1
kind: Pod
metadata:
  name: emptydir-demo
  namespace: default
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: emptydir-vol
          mountPath: /usr/share/nginx/html
    - name: almalinux
      image: almalinux:9
      command: ["sleep", "10000"]
      volumeMounts:
        - name: emptydir-vol
          mountPath: /mnt/nginx
  volumes:
    - name: emptydir-vol
      emptyDir: {}
