apiVersion: v1
kind: Pod
metadata:
  name: emptydir-demo
  namespace: default
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: emptydir-vol
          mountPath: /usr/share/nginx/html
  volumes:
    - name: emptydir-vol
      emptyDir: {}
