apiVersion: apps/v1
kind: Deployment
metadata:
  name: headless-demo
  namespace: default
  labels:
    purpose: headless-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      purpose: headless-demo
  template:
    metadata:
      labels:
        purpose: headless-demo
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "200m"
              memory: "250Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: headless-service
spec:
  selector:
    purpose: headless-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
