apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebspv-static
  namespace: default
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadwriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-076e6286becdbddbc
