apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebstsatic
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-076e6286becdbddbc
