# what we need in statefulset
# headless service,storage class,clusterIp service, pvc should not be written seperate.
#we have to write in statefulset only under volumeclaimtemplates
apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
spec:
  clusterIP: None
  selector:
    purpose: nginx-stateful
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    purpose: nginx-stateful
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
  labels:
    purpose: nginx-stateful
spec:
  replicas: 3
  serviceName: nginx-headless
  selector:
    matchLabels:
      purpose: nginx-stateful
  template:
    metadata:
      labels:
        purpose: nginx-stateful
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-volume
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: nginx-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "nginx-sc"
        resources:
          requests:
            storage: 1Gi

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nginx-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
