apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue-configmap
  namespace: roboshop
data:
  MONGO: true
  MONGO_URL: "mongodb://mongodb-service:27017/catalogue"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    component: catalogue
    tier: backend
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      component: catalogue
      tier: backend
      project: roboshop
  template:
    metadata:
      labels:
        component: catalogue
        tier: backend
        project: roboshop
    spec:
      containers:
        - name: catalogue
          image: joindevops/catalogue:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "150m"
              memory: "150Mi"
            limits:
              cpu: "200m"
              memory: "200Mi"
          envFrom:
            - configMapRef:
                name: catalogue-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue-service
  namespace: roboshop
spec:
  selector:
    component: catalogue
    tier: backend
    project: roboshop
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
