apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: roboshop
  labels:
    project: roboshop
spec:
  containers:
    - name: debug
      image: joindevops/debug:v1
      #command: ["sleep", "10000"]
