apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    component: mongodb
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mongodb
      tier: db
      project: roboshop
  template:
    metadata:
      labels:
        component: mongodb
        tier: db
        project: roboshop
    spec:
      containers:
        - name: mongodb
          image: joindevops/mongodb:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 20
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: roboshop
spec:
  selector:
    component: mongodb
    tier: db
    project: roboshop
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
