apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    component: mongodb
    project: roboshop
    tier: db
spec:
  replicas: 3
  selector:
    matchLabels:
      component: mongodb
      project: roboshop
      tier: db
  template:
    metadata:
      labels:
        component: mongodb
        project: roboshop
        tier: db
    spec:
      containers:
        - name: mongodb
          image: joindevops/mongodb:v1
          ports:
            - containerPort: 27017
          livenessProbe:
            tcpSocket:
              port: 27017
          readinessProbe:
            tcpSocket:
              port: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    component: mongodb
    project: roboshop
    tier: db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
