apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-configmap
  namespace: roboshop
data:
  CART_ENDPOINT: "cart-service:8080"
  DB_HOST: "mysql-service"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    component: shipping
    tier: backend
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      component: shipping
      tier: backend
      project: roboshop
  template:
    metadata:
      labels:
        component: shipping
        tier: backend
        project: roboshop
    spec:
      containers:
        - name: shipping
          image: joindevops/shipping:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          # resources:
          #   requests:
          #     cpu: "150m"
          #     memory: "150Mi"
          #   limits:
          #     cpu: "200m"
          #     memory: "200Mi"
          envFrom:
            - configMapRef:
                name: shipping-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-service
  namespace: roboshop
spec:
  selector:
    component: shipping
    tier: backend
    project: roboshop
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
