apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-statefulset
  labels:
    component: mongodb
    project: roboshop
    tier: db
spec:
  replicas: 2
  serviceName: "mongodb-headless"
  selector:
    matchLabels:
      component: mongodb
      project: roboshop
      tier: db
  template:
    metadata:
      labels:
        component: mongodb
        project: roboshop
        tier: db
    spec:
      containers:
        - name: mongodb
          image: joindevops/mongodb:v1
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-volume
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb-volume
      spec:
        storageClassName: "mongodb-storageclass"
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
spec:
  clusterIP: None
  selector:
    component: mongodb
    tier: db
    project: roboshop
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    component: mongodb
    tier: db
    project: roboshop
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongodb-storageclass
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
